### ISSUE TITLE
Need info of about the screenshot. 

### ISSUE THREAD

**Issue by vikas5914** [rdnlsmith/vscode-arc-theme#11]
HI,

I know this is not an issue, but can you tell me how to achieve the look in  this screenshot: 

https://raw.githubusercontent.com/SolarLiner/vscode-arc-theme/master/res/screen_adapta.png

**Comment by SolarLiner** [comment]
Of the editor or the whole desktop?

Closing for the issue counter.

**Comment by vikas5914** [comment]
Whole desktop

**Comment by SolarLiner** [comment]
DE is GNOME, with Dash to Panel put on top, and Dynamic Panel Transparency to control the opacity of the panel. Then it's Top Icons Plus and AppIndicator for the tray icons, Media Player Indicator for the media panel integration. The top left menu is Gno-Menu.  
The bottom dock is Plank.

I don't remember where the wallpaper comes from, I've changed a lot ever since :rofl:
