### ISSUE TITLE
Arc colors too washed out

### ISSUE THREAD

**Issue by al2me6** [rdnlsmith/vscode-arc-theme#12]
Just discovered this theme, it looks great!

However, I think the syntax highlighting colors are a bit too washed out to resemble the original color scheme.

**Comment by rdnlsmith** [comment]
Hi! I recently inherited this extension. Not being an Arc user myself, could you show me an example of what you're comparing with when you reference the "original color scheme"? Thanks!

**Comment by al2me6** [comment]
I'm not sure if this is the best example, but here is an example of a terminal using the Arc theme: 
![image](https://user-images.githubusercontent.com/35266431/47760264-c8113000-dc89-11e8-9c51-ea51b1f63ba1.png)
The colors are much more saturated than the current scheme. 

The current syntax highlighting theme is just copied from Base 16 Tomorrow, so perhaps if you don't have the time to create a completely new theme, perhaps using One Dark would be a close enough approximation?

**Comment by SolarLiner** [comment]
Note that this is *very* dependent on your terminal settings. You can easily change the ANSI colors that your terminal will reproduce (think base16 themes). AFAIK, Arc doesn't have an associated syntax theme.

I originally used the Tomorrow theme because it's what Ubuntu Budgie shipped Tilix with, and I thought it was a good fit. As I'm not exactly the best designer in town it may have had contrast issues, though I could read my code fine when using it.

**Comment by rdnlsmith** [comment]
I've put together a "better" (according to my subjective preferences) Arc Dark theme which leverages [tyriar/vscode-theme-generator](https://github.com/tyriar/vscode-theme-generator).

If you're interested in trying it out and giving me feedback, clone the repo and change to the `better_arc_dark` branch. Then, you can do one of two things:

1. run `npm install`, then open the repo in VS Code and press <kbd>F5</kbd>

or

2. Copy `./themes/dark/better-arc dark.json` to `~/.vscode/extensions/solarliner.linux-themes-1.0.1/themes`, then edit `~/.vscode/extensions/solarliner.linux-themes-1.0.1/package.json` to include these lines:

```json
{
  "label": "Better Arc Dark",
  "uiTheme": "vs-dark",
  "path": "./themes/better-arc dark.json"
},
```

Here's a preview image:

![better_arc_theme](https://user-images.githubusercontent.com/4039042/47938878-ccbd2a80-debb-11e8-85fc-34e1ea7dba47.png)

And for comparison, a similar shot of the original Arc Dark theme:

![arc_theme](https://user-images.githubusercontent.com/4039042/47938898-d8a8ec80-debb-11e8-8e92-40c742cc2b70.png)

**Comment by SolarLiner** [comment]
:+1: You're the captain now, and while I still prefer having the editor be lighter than the sidebar (which matches the colors of Files and Builder somewhat), the new theme does look good and I wish I had known about that theme generator before! :laughing: 

I'll add that I don't think we should duplicate the themes though. I'd say you should merge that new Arc theme into the old one.

**Comment by rdnlsmith** [comment]
@SolarLiner I was looking at the Settings app when I made the sidebar that color. Kinda funny that some apps are inverted relative to each other :stuck_out_tongue: Plus, the darker editor background helps with contrast.

![settings](https://user-images.githubusercontent.com/4039042/47954945-2b8bae00-df67-11e8-986a-8fb38a5a97b9.png)

I did intend to only have one Arc Dark theme ultimately, I just wanted to have both temporarily for comparison purposes.

I was hoping for a reply from @Al2Me6 too, since they were the one asking for changes.

**Comment by al2me6** [comment]
@rdnlsmith It certainly looks better! I do agree with your sidebar coloring, though the editor may now be a bit too dark. The title bar could also take a darker shade, like in your most recent screenshot.

I can try to come up with something, though I'm afraid I'm quite short on time (I'm a student).

**Comment by rdnlsmith** [comment]
@Al2Me6 Take 2. It feels a little low-contrast for my tastes, but it's still more vibrant than the original, and the background/sidebar colors now match the Settings app exactly. (The titlebar was already the same color, #2f343f.) Thoughts?

![better_arc_2](https://user-images.githubusercontent.com/4039042/48683507-92ba7c80-eb7b-11e8-8b94-8efb1cacaabb.png)

**Comment by rdnlsmith** [comment]
Version 1.1.0 includes a refreshed Arc Dark theme which addresses this issue.

This is the first release since I took ownership of the project, so the extension ID has changed to [rdnlsmith.linux-themes](https://marketplace.visualstudio.com/items?itemName=rdnlsmith.linux-themes). You will need to uninstall the existing extension and install the new one to get the update.
