### ISSUE TITLE
Right click menus are not themed

### ISSUE THREAD

**Issue by al2me6** [rdnlsmith/vscode-arc-theme#13]
As title states. I believe the ability to theme menus was recently added, is it possible to add this feature?

**Comment by rdnlsmith** [comment]
My understanding is that the menu theming only works if you have `"window.titleBarStyle": "custom"` in your settings. Basically, they re-implemented the title bar, menu bar, and context menu within VS Code, but they only use their version if you have that setting turned on. Otherwise, they use Electron's version, which doesn't pay attention to the VS Code theme.

I use the custom title bar, but I'm not a fan of how it looks like a Windows 10 title bar on Linux. So if you know something I don't, please send me a link!

**Comment by al2me6** [comment]
Sorry if I didn't make that clear, I was referring to context menus/right click menus.

**Comment by rdnlsmith** [comment]
I did understand that, but as far as I can tell, the context menu follows the same rules as the menu bar.

With custom title bar:

![theme_with_custom_bar](https://user-images.githubusercontent.com/4039042/47762370-d283f780-dc92-11e8-82e6-37df3e9934c8.png)

Without custom title bar:

![theme_not_custom](https://user-images.githubusercontent.com/4039042/47762384-dc0d5f80-dc92-11e8-9e73-7c96538ea9f1.png)

**Comment by al2me6** [comment]
You're indeed correct, my apologies. I did not realize that it used default GTK styling on Linux.

Nonetheless, the styling with custom title bars do seem a bit inappropriate... the color tone is too warm for the theme:

![image](https://user-images.githubusercontent.com/35266431/47762660-fb58bc80-dc93-11e8-82b8-e310fd67f63b.png)

![image](https://user-images.githubusercontent.com/35266431/47762611-c3ea1000-dc93-11e8-959c-11b0cdeb20ff.png)

![image](https://user-images.githubusercontent.com/35266431/47762554-8f765400-dc93-11e8-9a90-6da374781c8d.png)

**Comment by rdnlsmith** [comment]
Version 1.1.0 includes a refreshed Arc Dark theme which addresses this issue.

This is the first release since I took ownership of the project, so the extension ID has changed to [rdnlsmith.linux-themes](https://marketplace.visualstudio.com/items?itemName=rdnlsmith.linux-themes). You will need to uninstall the existing extension and install the new one to get the update.
