### ISSUE TITLE
Integrated terminal not themed

### ISSUE THREAD

**Issue by al2me6** [rdnlsmith/vscode-arc-theme#14]
Just noticed that the integrated terminal is also not themed. 

It would be great if you could fix this.

Sorry for the barrage of bug reports!

**Comment by rdnlsmith** [comment]
Version 1.1.0 includes a refreshed Arc Dark theme which addresses this issue.

This is the first release since I took ownership of the project, so the extension ID has changed to [rdnlsmith.linux-themes](https://marketplace.visualstudio.com/items?itemName=rdnlsmith.linux-themes). You will need to uninstall the existing extension and install the new one to get the update.
