### ISSUE TITLE
[Feature Request] Elementary Theme

### ISSUE THREAD

**Issue by joaopauloalbq** [rdnlsmith/vscode-arc-theme#19]

**Comment by rdnlsmith** [comment]
It's getting close! My goal was for it to resemble Elementary's own Code app. I don't use Elementary myself, so I'd appreciate feedback if you notice anything off.

I've uploaded a [preview release](https://github.com/rdnlsmith/vscode-arc-theme/releases/tag/v1.2.0-preview-1) to make it easy for you to try it out. Just download the `.vsix` file and run

```
code --install-extension linux-themes-1.2.0.vsix
```

![vscode-elementary](https://user-images.githubusercontent.com/4039042/61097282-c3139b80-a428-11e9-8bc1-836c5b1f9d0e.png)

**Comment by waldyrious** [comment]
Looks great, @rdnlsmith! I'd maybe add a bit more of a contrast difference between selected vs. unselected icons on the left sidebar, but overall it looks really good. I don't use Code myself though, so I can't comment on the faithfulness to the original design.

**Comment by joaopauloalbq** [comment]
Could you reduce the height of the tabs?

![vscode terminal](https://user-images.githubusercontent.com/9905202/61319011-b7372900-a7dc-11e9-8a46-bab0cb774891.png)

The side bar need a 1px border

![vscode ecode](https://user-images.githubusercontent.com/9905202/61319079-d59d2480-a7dc-11e9-83c2-8e764e6179d1.png)

I also changed some colors to match with Elementary theme.

![after before](https://user-images.githubusercontent.com/9905202/61319467-a6d37e00-a7dd-11e9-899c-9dc43bed6fc6.png)

**Comment by rdnlsmith** [comment]
@joaopauloalbq 

> Could you reduce the height of the tabs?

> The side bar need a 1px border

Unfortunately, VS Code themes can only set colors. There's currently no way for a theme to override shapes/sizes/positions/etc. of UI elements. [Here](https://github.com/microsoft/vscode/issues/26129) is a relevant open issue, but it doesn't appear very active. You could also try combining this theme with [this custom CSS extension](https://github.com/be5invis/vscode-custom-css) if you want. Note that the VS Code devs have [stated](https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312) that it isn't feasible for them to officially support custom CSS.

> I also changed some colors to match with Elementary theme.

Could you list out what you changed, ideally with color hex values? The only change that's visually apparent to me is the lighter gray on the activity bar, which looks like it roughly matches the sidebar color in Elementary Code.

I chose to have the VS Code sidebar (explorer pane, etc.) match the Elementary Code sidebar. I made the activity bar (icons) a bit darker so it would match the menu bar and the (focused) title bar, and also because I like to have some contrast between the sidebar and the activity bar.

**Comment by rdnlsmith** [comment]
@waldyrious You are talking about this? You're right, I should probably make the inactive icons lighter. I had set the active icon color to match the UI text color.

![image](https://user-images.githubusercontent.com/4039042/61339209-b6b58700-a80a-11e9-8c00-89ec7811441a.png)

**Comment by joaopauloalbq** [comment]
Got it!

>  The only change that's visually apparent to me is the lighter gray on the activity bar, which looks like it roughly matches the sidebar color in Elementary Code.

That's it, lighter gray on the side bar and darker icons.

**Comment by waldyrious** [comment]
> @waldyrious You are talking about this?

Yes.

> I should probably make the inactive icons lighter.

SGTM!

**Comment by rdnlsmith** [comment]
Elementary theme was included in [v1.2.0](https://github.com/rdnlsmith/vscode-linux-themes/releases/tag/v1.2.0), published today (2020-07-05).

**Comment by waldyrious** [comment]
@rdnlsmith I know the README would get too long if we included all styles; what do you think about a gallery page (i.e. another markdown file) with the names and screenshots of all themes?

**Comment by rdnlsmith** [comment]
@waldyrious Yes, I think that is a good idea. In addition, I think it would be nice to also have a grid of smaller thumbnail images still in the README. I’d be interested to see if a version of [this site](https://vscodethemes.com/) could be run locally in order to generate thumbnails (the hosted version appears to be limited to a handful of themes per extension).

Feel free to create a separate issue for this, and/or submit a PR if you have time! Otherwise, I will get around to it.

**Comment by waldyrious** [comment]
> In addition, I think it would be nice to also have a grid of smaller thumbnail images still in the README

That was exactly what I had in mind and was going to propose next! :)

> Feel free to create a separate issue for this, and/or submit a PR if you have time! Otherwise, I will get around to it.

Will do! I may be able to work on this sometime during this week, but no promise! 😄
