### ISSUE TITLE
Yaru: tiny improvements

### ISSUE THREAD

**Issue by Feichtmeier** [rdnlsmith/vscode-arc-theme#28]
**Version Info**
- Theme: Yaru (not dark)

**Description**
1. the badges are orange, but in yaru they are green ```#0e8420``` 
2. The terminal is correctly purple as in yaru but in a super white window, this hardcore contrast to the dark purple is imho too much therefor I would suggest ```#f7f7f7``` for the background and ```#3b3b3b``` for the foreground
3. The selection color is dark purple with a dark foreground in the light yaru version. The selected text is unreadable, I did not find the correct color for the foreground color but I would either suggest to somehow transparentize the purple or to have a white selection text color :) 
![grafik](https://user-images.githubusercontent.com/15329494/87422824-9bc25200-c5d9-11ea-9624-3428225748b3.png)

**Screenshots**
Screenshot of the suggestion:
![Bildschirmfoto von 2020-07-14 13-52-25](https://user-images.githubusercontent.com/15329494/87422665-543bc600-c5d9-11ea-9f94-64fc299eff79.png)

Thanks for bringing yaru to vscode and best regards :beer:

**Comment by rdnlsmith** [comment]
Hi, thanks for the issue! (And the PR!)

Would you mind sharing how you got the badge color of `#0e8420`? I took and inspected screenshots of the "Updates" badge in the Software Center and got `#109b26` for light/standard and `#0c6d1a` for dark. I don't really see badges much in my day-to-day usage, so I didn't actually know the correct color before now. I'm using the 20.04 version of Yaru if that makes a difference.

I don't remember how I decided on the highlight color&mdash;I may just have wanted something "Ubuntu-ish". I notice that text highlighting in gedit is orange. I'll have to give it some thought.

Regarding the terminal, I certainly see your point about the contrast. On the other hand, I very much wanted the built-in terminal to look exactly like the default Ubuntu terminal theme&mdash;indeed, this was the idea which led me to create the Yaru VS Code themes in the first place. To me, the terminal appearance is almost the "soul" of the theme; without it, I think it feels like a much more generic light theme. To my knowledge, there isn't a default light variant of the Ubuntu terminal theme (I'd be glad to be corrected here), so I'm inclined to keep the purple terminal in the theme, and allow users who have customized their Ubuntu terminals to also customize the VS Code terminal colors in their `settings.json`. What do you think about that?

I _might_ also consider darkening the color of the rest of the bottom panel if that would reduce the contrast sufficiently, without feeling un-Yaru-like.

Regarding the PR, I see you edited `themes/light/yaru.json`. However&mdash;and I recognize this is probably not obvious&mdash;that file is actually generated from `themes/src/light/yaru.ts` using [tyriar/vscode-theme-generator](https://github.com/tyriar/vscode-theme-generator). I only keep the `.json` version in Git so that I will notice if an update to the generator changes a color key which I wasn't expecting. I should probably update the `CONTRIBUTING.md` file and/or create a wiki to make this easier to discover.

**Comment by Feichtmeier** [comment]
Hi thanks for the reply!
Yeah the green is our base green from our palette. However, I've just remembered that we've darkened it a bit with scss built in mixins... I think you're correct about that green but I need to look up the returned hexvalue myself.
On the terminal I totally understand what you mean, it's just that I use your yaru theme as my light theme at day, so when I look down to the dark part it almost hurts how heavy the contrast is. In the stand alone terminal in Ubuntu it is drawn in a dark window.
I'll fix the green in the pr and remove the terminal colour change for now because I think we can agree on this one, right? :)

**Comment by Feichtmeier** [comment]
Green you proposed confirmed :)
![grafik](https://user-images.githubusercontent.com/15329494/87519995-a684f180-c682-11ea-8483-effe67a0b26f.png)
Changed the PR and reverted the terminal change

**Comment by rdnlsmith** [comment]
Sounds good! I've left a review on the PR.

I imagine you're probably aware of this, but just in case: I described in #18 how to override terminal colors in `settings.json`, so you can make your personal terminal experience less painful :slightly_smiling_face:
