### ISSUE TITLE
Difference between SolarLiner and rdnlsmith?

### ISSUE THREAD

**Issue by ChayoteJarocho** [rdnlsmith/vscode-arc-theme#43]
When I search for "Linux Themes for VS Code" in the extensions search textbox, I get two results: 

- One submitted by the user SolarLiner, with 601K downloads, a Details description with broken links to images, and the Changelog saying this is the initial version.
- Another one submitted by rdnlsmith, with 30K downloads, a Details description with correctly loaded links to images, and the Changelog showing actual version history.

Both have in the Details description a link to this repo, at the very bottom.

So what's the difference? Which one should I install? Are both yours?

**Comment by rdnlsmith** [comment]
This was originally SolarLiner's project. He transferred the repository to me in October 2018, which is why both extensions point to the same place. Unfortunately, it's not really possible to transfer ownership of a VS Code extension, so I had to publish my own version.

Mine has a few themes that SolarLiner's doesn't: Yaru, Yaru Dark, Elementary. I also substantially changed the Arc Dark theme.

However, I'm not actively working on improvements, so which one you should install depends on whether you want any of the new themes listed above or whether you prefer the original version of Arc Dark.

**Comment by ChayoteJarocho** [comment]
Thanks for the details. I'll close this since my question was answered.
